// ============================================================================
// CARDVERSE HIDDEN DIGITAL CARD SYSTEM
// The Ultimate Engagement Engine - Hidden collectible cards throughout the app
// ============================================================================

// Rarity Configuration
export const RARITY_CONFIG = {
  common: {
    name: 'Common',
    color: '#9CA3AF',
    bgGradient: 'from-gray-400 to-gray-600',
    glowColor: 'rgba(156, 163, 175, 0.5)',
    dropChance: 40,
    icon: '⬜',
  },
  uncommon: {
    name: 'Uncommon',
    color: '#22C55E',
    bgGradient: 'from-green-400 to-green-600',
    glowColor: 'rgba(34, 197, 94, 0.5)',
    dropChance: 25,
    icon: '🟩',
  },
  rare: {
    name: 'Rare',
    color: '#3B82F6',
    bgGradient: 'from-blue-400 to-blue-600',
    glowColor: 'rgba(59, 130, 246, 0.5)',
    dropChance: 18,
    icon: '🟦',
  },
  epic: {
    name: 'Epic',
    color: '#A855F7',
    bgGradient: 'from-purple-400 to-purple-600',
    glowColor: 'rgba(168, 85, 247, 0.5)',
    dropChance: 10,
    icon: '🟪',
  },
  legendary: {
    name: 'Legendary',
    color: '#F59E0B',
    bgGradient: 'from-amber-400 to-orange-600',
    glowColor: 'rgba(245, 158, 11, 0.6)',
    dropChance: 5,
    icon: '🟨',
  },
  mythic: {
    name: 'Mythic',
    color: '#EC4899',
    bgGradient: 'from-pink-400 via-rose-500 to-red-600',
    glowColor: 'rgba(236, 72, 153, 0.7)',
    dropChance: 2,
    icon: '💎',
  },
} as const;

export type Rarity = keyof typeof RARITY_CONFIG;

// Element Types
export const ELEMENTS = {
  fire: { name: 'Fire', color: '#EF4444', icon: '🔥', emoji: '🔥' },
  water: { name: 'Water', color: '#3B82F6', icon: '💧', emoji: '💧' },
  earth: { name: 'Earth', color: '#84CC16', icon: '🌿', emoji: '🌿' },
  air: { name: 'Air', color: '#06B6D4', icon: '💨', emoji: '💨' },
  light: { name: 'Light', color: '#FBBF24', icon: '✨', emoji: '✨' },
  dark: { name: 'Dark', color: '#6366F1', icon: '🌙', emoji: '🌙' },
  neutral: { name: 'Neutral', color: '#9CA3AF', icon: '⚪', emoji: '⚪' },
} as const;

export type Element = keyof typeof ELEMENTS;

// Discovery Types - How cards can be found
export const DISCOVERY_TYPES = {
  feature_use: 'Use a specific feature X times',
  achievement: 'Unlock an achievement',
  secret: 'Find a hidden easter egg',
  event: 'Participate in a special event',
  random: 'Random drop while using the app',
  purchase: 'Available for purchase',
  streak: 'Maintain a login streak',
  social: 'Invite friends or share content',
  collection: 'Complete a collection milestone',
  trivia: 'Answer trivia questions correctly',
  club: 'Join or create a club',
  first: 'Be among the first to do something',
} as const;

export type DiscoveryType = keyof typeof DISCOVERY_TYPES;

// Digital Card Interface
export interface DigitalCard {
  id: string;
  cardCode: string;
  name: string;
  description: string;
  imageUrl?: string;
  rarity: Rarity;
  series: string;
  seriesNumber: number;
  totalInSeries: number;
  discoveryType: DiscoveryType;
  discoveryTrigger: Record<string, unknown>;
  discoveryHint: string;
  powerLevel: number;
  element: Element;
  cardType: 'character' | 'artifact' | 'location' | 'event' | 'boost';
  maxSupply?: number;
  currentSupply: number;
  isActive: boolean;
}

// User's Card Instance
export interface UserDigitalCard {
  id: string;
  cardId: string;
  card: DigitalCard;
  discoveredAt: string;
  discoveryLocation: string;
  instanceNumber: number;
  isFoil: boolean;
  isFirstEdition: boolean;
  isFavorite: boolean;
}

// ============================================================================
// CARD SERIES DEFINITIONS
// ============================================================================

export const CARD_SERIES = {
  FOUNDER: {
    code: 'FOUNDER',
    name: 'Founder Series',
    description: 'Exclusive cards for early CardVerse adopters. These cards will never be available again.',
    totalCards: 10,
    theme: 'Origins & Legacy',
    completionReward: { type: 'title', value: 'Founding Collector' },
  },
  EXPLORER: {
    code: 'EXPLORER',
    name: 'Explorer Series',
    description: 'Discover these cards by exploring every corner of CardVerse.',
    totalCards: 25,
    theme: 'Discovery & Adventure',
    completionReward: { type: 'badge', value: 'Master Explorer' },
  },
  KNOWLEDGE: {
    code: 'KNOWLEDGE',
    name: 'Knowledge Keeper Series',
    description: 'Earned through trivia mastery and learning in the Card Academy.',
    totalCards: 20,
    theme: 'Wisdom & Learning',
    completionReward: { type: 'special_card', value: 'MYTHIC_SCHOLAR' },
  },
  COMMUNITY: {
    code: 'COMMUNITY',
    name: 'Community Champions',
    description: 'Cards earned through club participation and social engagement.',
    totalCards: 15,
    theme: 'Friendship & Unity',
    completionReward: { type: 'title', value: 'Community Champion' },
  },
  LEGENDS: {
    code: 'LEGENDS',
    name: 'Legends of CardVerse',
    description: 'Ultra-rare cards featuring iconic moments in trading card history.',
    totalCards: 12,
    theme: 'History & Legacy',
    completionReward: { type: 'special_card', value: 'MYTHIC_HISTORIAN' },
  },
  SEASONS: {
    code: 'SEASONS',
    name: 'Seasonal Treasures',
    description: 'Limited-time cards available only during special seasons and events.',
    totalCards: 24,
    theme: 'Time & Celebration',
    completionReward: { type: 'badge', value: 'Season Master' },
  },
  SECRETS: {
    code: 'SECRETS',
    name: 'Secret Vault',
    description: 'The rarest cards hidden in the deepest secrets of CardVerse. Can you find them all?',
    totalCards: 8,
    theme: 'Mystery & Intrigue',
    completionReward: { type: 'special_card', value: 'MYTHIC_SHADOW' },
  },
};

// ============================================================================
// COMPLETE CARD DEFINITIONS - 100+ Hidden Digital Cards
// ============================================================================

export const DIGITAL_CARDS: Omit<DigitalCard, 'id' | 'currentSupply'>[] = [
  // ==================== FOUNDER SERIES (10 cards) ====================
  {
    cardCode: 'FOUNDER_001',
    name: 'Genesis Collector',
    description: 'Awarded to those who joined CardVerse in its first month. A symbol of trust in the beginning.',
    rarity: 'legendary',
    series: 'FOUNDER',
    seriesNumber: 1,
    totalInSeries: 10,
    discoveryType: 'first',
    discoveryTrigger: { action: 'account_create', within_days: 30 },
    discoveryHint: 'Be among the first to believe in CardVerse.',
    powerLevel: 100,
    element: 'light',
    cardType: 'character',
    maxSupply: 1000,
    isActive: true,
  },
  {
    cardCode: 'FOUNDER_002',
    name: 'Trailblazer',
    description: 'For those who added their first 10 cards before anyone else knew what CardVerse would become.',
    rarity: 'epic',
    series: 'FOUNDER',
    seriesNumber: 2,
    totalInSeries: 10,
    discoveryType: 'collection',
    discoveryTrigger: { cards_added: 10, within_days: 7 },
    discoveryHint: 'Add 10 cards to your collection within your first week.',
    powerLevel: 80,
    element: 'fire',
    cardType: 'character',
    maxSupply: 5000,
    isActive: true,
  },
  {
    cardCode: 'FOUNDER_003',
    name: 'Pioneer Spirit',
    description: 'Explorers who visited every section of CardVerse before the crowds arrived.',
    rarity: 'rare',
    series: 'FOUNDER',
    seriesNumber: 3,
    totalInSeries: 10,
    discoveryType: 'feature_use',
    discoveryTrigger: { features: ['collection', 'museum', 'trivia', 'clubs', 'javari'] },
    discoveryHint: 'Visit every major section of CardVerse.',
    powerLevel: 60,
    element: 'air',
    cardType: 'artifact',
    isActive: true,
  },
  {
    cardCode: 'FOUNDER_004',
    name: 'First Question',
    description: 'Asked Javari AI their very first question. The beginning of a beautiful friendship.',
    rarity: 'uncommon',
    series: 'FOUNDER',
    seriesNumber: 4,
    totalInSeries: 10,
    discoveryType: 'feature_use',
    discoveryTrigger: { feature: 'javari', uses: 1 },
    discoveryHint: 'Have your first conversation with Javari.',
    powerLevel: 40,
    element: 'neutral',
    cardType: 'event',
    isActive: true,
  },
  {
    cardCode: 'FOUNDER_005',
    name: 'Community Seed',
    description: 'Planted the first seeds of community by joining their first club.',
    rarity: 'uncommon',
    series: 'FOUNDER',
    seriesNumber: 5,
    totalInSeries: 10,
    discoveryType: 'club',
    discoveryTrigger: { action: 'join_club', count: 1 },
    discoveryHint: 'Join your first CardVerse club.',
    powerLevel: 35,
    element: 'earth',
    cardType: 'location',
    isActive: true,
  },
  {
    cardCode: 'FOUNDER_006',
    name: 'Wisdom Seeker',
    description: 'Completed their first trivia quiz, beginning their journey of card knowledge.',
    rarity: 'common',
    series: 'FOUNDER',
    seriesNumber: 6,
    totalInSeries: 10,
    discoveryType: 'trivia',
    discoveryTrigger: { quizzes_completed: 1 },
    discoveryHint: 'Complete your first trivia quiz.',
    powerLevel: 25,
    element: 'light',
    cardType: 'event',
    isActive: true,
  },
  {
    cardCode: 'FOUNDER_007',
    name: 'History Walker',
    description: 'Took their first steps through the Card History Museum.',
    rarity: 'common',
    series: 'FOUNDER',
    seriesNumber: 7,
    totalInSeries: 10,
    discoveryType: 'feature_use',
    discoveryTrigger: { feature: 'museum', uses: 1 },
    discoveryHint: 'Visit the Card History Museum.',
    powerLevel: 20,
    element: 'dark',
    cardType: 'location',
    isActive: true,
  },
  {
    cardCode: 'FOUNDER_008',
    name: 'Collection Born',
    description: 'Added their very first card to CardVerse. Every journey begins with a single card.',
    rarity: 'common',
    series: 'FOUNDER',
    seriesNumber: 8,
    totalInSeries: 10,
    discoveryType: 'collection',
    discoveryTrigger: { cards_added: 1 },
    discoveryHint: 'Add your first card to your collection.',
    powerLevel: 15,
    element: 'neutral',
    cardType: 'artifact',
    isActive: true,
  },
  {
    cardCode: 'FOUNDER_009',
    name: 'Profile Crafter',
    description: 'Took the time to personalize their CardVerse profile.',
    rarity: 'common',
    series: 'FOUNDER',
    seriesNumber: 9,
    totalInSeries: 10,
    discoveryType: 'feature_use',
    discoveryTrigger: { action: 'complete_profile' },
    discoveryHint: 'Complete your CardVerse profile.',
    powerLevel: 10,
    element: 'water',
    cardType: 'character',
    isActive: true,
  },
  {
    cardCode: 'FOUNDER_010',
    name: 'Founder\'s Flame',
    description: 'The ultimate Founder card. Completed the entire Founder Series. You were here from the start.',
    rarity: 'mythic',
    series: 'FOUNDER',
    seriesNumber: 10,
    totalInSeries: 10,
    discoveryType: 'collection',
    discoveryTrigger: { series_complete: 'FOUNDER' },
    discoveryHint: 'Collect all other Founder Series cards.',
    powerLevel: 150,
    element: 'fire',
    cardType: 'character',
    maxSupply: 500,
    isActive: true,
  },

  // ==================== EXPLORER SERIES (25 cards) ====================
  {
    cardCode: 'EXPLORER_001',
    name: 'Curious Wanderer',
    description: 'Clicked on 50 different things in CardVerse. Curiosity is the key to discovery.',
    rarity: 'common',
    series: 'EXPLORER',
    seriesNumber: 1,
    totalInSeries: 25,
    discoveryType: 'feature_use',
    discoveryTrigger: { clicks: 50 },
    discoveryHint: 'Explore and click around CardVerse.',
    powerLevel: 15,
    element: 'air',
    cardType: 'character',
    isActive: true,
  },
  {
    cardCode: 'EXPLORER_002',
    name: 'Night Owl',
    description: 'Discovered the platform during the quiet hours. Some treasures are only found at night.',
    rarity: 'uncommon',
    series: 'EXPLORER',
    seriesNumber: 2,
    totalInSeries: 25,
    discoveryType: 'secret',
    discoveryTrigger: { time_range: { start: '00:00', end: '04:00' } },
    discoveryHint: 'Visit CardVerse between midnight and 4 AM.',
    powerLevel: 35,
    element: 'dark',
    cardType: 'character',
    isActive: true,
  },
  {
    cardCode: 'EXPLORER_003',
    name: 'Early Bird',
    description: 'The early collector gets the card. Found exploring before dawn.',
    rarity: 'uncommon',
    series: 'EXPLORER',
    seriesNumber: 3,
    totalInSeries: 25,
    discoveryType: 'secret',
    discoveryTrigger: { time_range: { start: '05:00', end: '07:00' } },
    discoveryHint: 'Visit CardVerse at the crack of dawn.',
    powerLevel: 35,
    element: 'light',
    cardType: 'character',
    isActive: true,
  },
  {
    cardCode: 'EXPLORER_004',
    name: 'Scroll Master',
    description: 'Scrolled through thousands of cards. The depth of exploration knows no bounds.',
    rarity: 'rare',
    series: 'EXPLORER',
    seriesNumber: 4,
    totalInSeries: 25,
    discoveryType: 'feature_use',
    discoveryTrigger: { scroll_distance: 10000 },
    discoveryHint: 'Scroll through many, many cards.',
    powerLevel: 50,
    element: 'earth',
    cardType: 'artifact',
    isActive: true,
  },
  {
    cardCode: 'EXPLORER_005',
    name: 'Search Sage',
    description: 'Performed 100 searches. A master of finding what they seek.',
    rarity: 'rare',
    series: 'EXPLORER',
    seriesNumber: 5,
    totalInSeries: 25,
    discoveryType: 'feature_use',
    discoveryTrigger: { searches: 100 },
    discoveryHint: 'Search for cards frequently.',
    powerLevel: 55,
    element: 'light',
    cardType: 'artifact',
    isActive: true,
  },
  {
    cardCode: 'EXPLORER_006',
    name: 'Filter Fanatic',
    description: 'Used every single filter option available. Precision is an art.',
    rarity: 'epic',
    series: 'EXPLORER',
    seriesNumber: 6,
    totalInSeries: 25,
    discoveryType: 'feature_use',
    discoveryTrigger: { all_filters_used: true },
    discoveryHint: 'Try every filter option in the collection view.',
    powerLevel: 70,
    element: 'water',
    cardType: 'artifact',
    isActive: true,
  },
  {
    cardCode: 'EXPLORER_007',
    name: 'Hidden Button',
    description: 'Found the secret button hidden in the footer. You have a keen eye.',
    rarity: 'legendary',
    series: 'EXPLORER',
    seriesNumber: 7,
    totalInSeries: 25,
    discoveryType: 'secret',
    discoveryTrigger: { easter_egg: 'footer_secret' },
    discoveryHint: 'Some secrets hide in plain sight... at the bottom.',
    powerLevel: 95,
    element: 'dark',
    cardType: 'artifact',
    maxSupply: 2000,
    isActive: true,
  },
  {
    cardCode: 'EXPLORER_008',
    name: 'Konami Code Master',
    description: '↑↑↓↓←→←→BA - You know the ancient ways.',
    rarity: 'legendary',
    series: 'EXPLORER',
    seriesNumber: 8,
    totalInSeries: 25,
    discoveryType: 'secret',
    discoveryTrigger: { easter_egg: 'konami_code' },
    discoveryHint: 'Enter a legendary code known to all gamers.',
    powerLevel: 100,
    element: 'fire',
    cardType: 'event',
    maxSupply: 1000,
    isActive: true,
  },
  {
    cardCode: 'EXPLORER_009',
    name: 'Weekend Warrior',
    description: 'Visited CardVerse every weekend for a month.',
    rarity: 'rare',
    series: 'EXPLORER',
    seriesNumber: 9,
    totalInSeries: 25,
    discoveryType: 'streak',
    discoveryTrigger: { weekends: 4 },
    discoveryHint: 'Visit every weekend for a month.',
    powerLevel: 60,
    element: 'fire',
    cardType: 'character',
    isActive: true,
  },
  {
    cardCode: 'EXPLORER_010',
    name: 'Daily Devotee',
    description: 'Logged in for 7 consecutive days. Dedication rewarded.',
    rarity: 'uncommon',
    series: 'EXPLORER',
    seriesNumber: 10,
    totalInSeries: 25,
    discoveryType: 'streak',
    discoveryTrigger: { daily_streak: 7 },
    discoveryHint: 'Log in 7 days in a row.',
    powerLevel: 40,
    element: 'earth',
    cardType: 'boost',
    isActive: true,
  },
  {
    cardCode: 'EXPLORER_011',
    name: 'Month Marathon',
    description: 'An incredible 30-day login streak. Your dedication is legendary.',
    rarity: 'epic',
    series: 'EXPLORER',
    seriesNumber: 11,
    totalInSeries: 25,
    discoveryType: 'streak',
    discoveryTrigger: { daily_streak: 30 },
    discoveryHint: 'Log in every day for a month.',
    powerLevel: 85,
    element: 'fire',
    cardType: 'boost',
    isActive: true,
  },
  {
    cardCode: 'EXPLORER_012',
    name: 'Year of Cards',
    description: 'A full year of CardVerse exploration. You are truly dedicated.',
    rarity: 'mythic',
    series: 'EXPLORER',
    seriesNumber: 12,
    totalInSeries: 25,
    discoveryType: 'streak',
    discoveryTrigger: { daily_streak: 365 },
    discoveryHint: 'The ultimate dedication: 365 days.',
    powerLevel: 200,
    element: 'light',
    cardType: 'character',
    maxSupply: 100,
    isActive: true,
  },
  // More Explorer cards...
  {
    cardCode: 'EXPLORER_013',
    name: 'Mobile Pioneer',
    description: 'First accessed CardVerse from a mobile device.',
    rarity: 'common',
    series: 'EXPLORER',
    seriesNumber: 13,
    totalInSeries: 25,
    discoveryType: 'feature_use',
    discoveryTrigger: { platform: 'mobile' },
    discoveryHint: 'Visit CardVerse from your phone.',
    powerLevel: 20,
    element: 'air',
    cardType: 'artifact',
    isActive: true,
  },
  {
    cardCode: 'EXPLORER_014',
    name: 'Tab Hoarder',
    description: 'Had 5 CardVerse tabs open simultaneously. A true multitasker.',
    rarity: 'rare',
    series: 'EXPLORER',
    seriesNumber: 14,
    totalInSeries: 25,
    discoveryType: 'secret',
    discoveryTrigger: { tabs_open: 5 },
    discoveryHint: 'Open multiple CardVerse tabs at once.',
    powerLevel: 45,
    element: 'water',
    cardType: 'artifact',
    isActive: true,
  },
  {
    cardCode: 'EXPLORER_015',
    name: 'Dark Mode Knight',
    description: 'Switched to dark mode. The shadows welcome you.',
    rarity: 'common',
    series: 'EXPLORER',
    seriesNumber: 15,
    totalInSeries: 25,
    discoveryType: 'feature_use',
    discoveryTrigger: { action: 'enable_dark_mode' },
    discoveryHint: 'Toggle dark mode in settings.',
    powerLevel: 25,
    element: 'dark',
    cardType: 'boost',
    isActive: true,
  },

  // ==================== KNOWLEDGE KEEPER SERIES (20 cards) ====================
  {
    cardCode: 'KNOWLEDGE_001',
    name: 'Trivia Novice',
    description: 'Answered 10 trivia questions correctly. Knowledge is power.',
    rarity: 'common',
    series: 'KNOWLEDGE',
    seriesNumber: 1,
    totalInSeries: 20,
    discoveryType: 'trivia',
    discoveryTrigger: { correct_answers: 10 },
    discoveryHint: 'Answer 10 trivia questions correctly.',
    powerLevel: 15,
    element: 'light',
    cardType: 'boost',
    isActive: true,
  },
  {
    cardCode: 'KNOWLEDGE_002',
    name: 'Trivia Adept',
    description: 'Answered 50 trivia questions correctly. Your knowledge grows.',
    rarity: 'uncommon',
    series: 'KNOWLEDGE',
    seriesNumber: 2,
    totalInSeries: 20,
    discoveryType: 'trivia',
    discoveryTrigger: { correct_answers: 50 },
    discoveryHint: 'Answer 50 trivia questions correctly.',
    powerLevel: 35,
    element: 'light',
    cardType: 'boost',
    isActive: true,
  },
  {
    cardCode: 'KNOWLEDGE_003',
    name: 'Trivia Master',
    description: 'Answered 100 trivia questions correctly. A walking encyclopedia.',
    rarity: 'rare',
    series: 'KNOWLEDGE',
    seriesNumber: 3,
    totalInSeries: 20,
    discoveryType: 'trivia',
    discoveryTrigger: { correct_answers: 100 },
    discoveryHint: 'Answer 100 trivia questions correctly.',
    powerLevel: 55,
    element: 'light',
    cardType: 'character',
    isActive: true,
  },
  {
    cardCode: 'KNOWLEDGE_004',
    name: 'Perfect Round',
    description: 'Got every question right in a single trivia session.',
    rarity: 'epic',
    series: 'KNOWLEDGE',
    seriesNumber: 4,
    totalInSeries: 20,
    discoveryType: 'trivia',
    discoveryTrigger: { perfect_round: true },
    discoveryHint: 'Complete a perfect trivia round.',
    powerLevel: 75,
    element: 'fire',
    cardType: 'event',
    isActive: true,
  },
  {
    cardCode: 'KNOWLEDGE_005',
    name: 'Speed Demon',
    description: 'Answered 5 questions in under 30 seconds total. Lightning fast!',
    rarity: 'rare',
    series: 'KNOWLEDGE',
    seriesNumber: 5,
    totalInSeries: 20,
    discoveryType: 'trivia',
    discoveryTrigger: { speed_round: { questions: 5, seconds: 30 } },
    discoveryHint: 'Answer questions incredibly fast.',
    powerLevel: 50,
    element: 'air',
    cardType: 'boost',
    isActive: true,
  },
  {
    cardCode: 'KNOWLEDGE_006',
    name: 'Pokémon Professor',
    description: 'Mastered all Pokémon trivia categories.',
    rarity: 'epic',
    series: 'KNOWLEDGE',
    seriesNumber: 6,
    totalInSeries: 20,
    discoveryType: 'trivia',
    discoveryTrigger: { category_mastery: 'pokemon' },
    discoveryHint: 'Master all Pokémon trivia.',
    powerLevel: 80,
    element: 'fire',
    cardType: 'character',
    isActive: true,
  },
  {
    cardCode: 'KNOWLEDGE_007',
    name: 'MTG Archmage',
    description: 'Mastered all Magic: The Gathering trivia categories.',
    rarity: 'epic',
    series: 'KNOWLEDGE',
    seriesNumber: 7,
    totalInSeries: 20,
    discoveryType: 'trivia',
    discoveryTrigger: { category_mastery: 'mtg' },
    discoveryHint: 'Master all MTG trivia.',
    powerLevel: 80,
    element: 'water',
    cardType: 'character',
    isActive: true,
  },
  {
    cardCode: 'KNOWLEDGE_008',
    name: 'Sports Sage',
    description: 'Mastered all sports card trivia categories.',
    rarity: 'epic',
    series: 'KNOWLEDGE',
    seriesNumber: 8,
    totalInSeries: 20,
    discoveryType: 'trivia',
    discoveryTrigger: { category_mastery: 'sports' },
    discoveryHint: 'Master all sports card trivia.',
    powerLevel: 80,
    element: 'earth',
    cardType: 'character',
    isActive: true,
  },
  {
    cardCode: 'KNOWLEDGE_009',
    name: 'History Scholar',
    description: 'Read through the entire Card History Museum.',
    rarity: 'rare',
    series: 'KNOWLEDGE',
    seriesNumber: 9,
    totalInSeries: 20,
    discoveryType: 'feature_use',
    discoveryTrigger: { museum_sections_viewed: 'all' },
    discoveryHint: 'Read every section of the Museum.',
    powerLevel: 60,
    element: 'dark',
    cardType: 'character',
    isActive: true,
  },
  {
    cardCode: 'KNOWLEDGE_010',
    name: 'Javari\'s Apprentice',
    description: 'Had 25 conversations with Javari AI.',
    rarity: 'rare',
    series: 'KNOWLEDGE',
    seriesNumber: 10,
    totalInSeries: 20,
    discoveryType: 'feature_use',
    discoveryTrigger: { javari_conversations: 25 },
    discoveryHint: 'Chat with Javari regularly.',
    powerLevel: 55,
    element: 'neutral',
    cardType: 'character',
    isActive: true,
  },

  // ==================== COMMUNITY CHAMPIONS (15 cards) ====================
  {
    cardCode: 'COMMUNITY_001',
    name: 'Club Founder',
    description: 'Created a club and welcomed the community.',
    rarity: 'rare',
    series: 'COMMUNITY',
    seriesNumber: 1,
    totalInSeries: 15,
    discoveryType: 'club',
    discoveryTrigger: { action: 'create_club' },
    discoveryHint: 'Create your own club.',
    powerLevel: 60,
    element: 'earth',
    cardType: 'location',
    isActive: true,
  },
  {
    cardCode: 'COMMUNITY_002',
    name: 'Social Butterfly',
    description: 'Joined 5 different clubs.',
    rarity: 'uncommon',
    series: 'COMMUNITY',
    seriesNumber: 2,
    totalInSeries: 15,
    discoveryType: 'club',
    discoveryTrigger: { clubs_joined: 5 },
    discoveryHint: 'Join 5 clubs.',
    powerLevel: 40,
    element: 'air',
    cardType: 'character',
    isActive: true,
  },
  {
    cardCode: 'COMMUNITY_003',
    name: 'Rally Leader',
    description: 'Your club reached 10 members.',
    rarity: 'epic',
    series: 'COMMUNITY',
    seriesNumber: 3,
    totalInSeries: 15,
    discoveryType: 'club',
    discoveryTrigger: { club_members: 10 },
    discoveryHint: 'Grow your club to 10 members.',
    powerLevel: 75,
    element: 'fire',
    cardType: 'character',
    isActive: true,
  },
  {
    cardCode: 'COMMUNITY_004',
    name: 'Trade Partner',
    description: 'Completed your first trade with another collector.',
    rarity: 'uncommon',
    series: 'COMMUNITY',
    seriesNumber: 4,
    totalInSeries: 15,
    discoveryType: 'social',
    discoveryTrigger: { trades_completed: 1 },
    discoveryHint: 'Complete a trade.',
    powerLevel: 35,
    element: 'water',
    cardType: 'event',
    isActive: true,
  },
  {
    cardCode: 'COMMUNITY_005',
    name: 'Helpful Hand',
    description: 'Answered a question in a club forum.',
    rarity: 'common',
    series: 'COMMUNITY',
    seriesNumber: 5,
    totalInSeries: 15,
    discoveryType: 'social',
    discoveryTrigger: { forum_posts: 1 },
    discoveryHint: 'Help others in club discussions.',
    powerLevel: 20,
    element: 'light',
    cardType: 'boost',
    isActive: true,
  },

  // ==================== SECRETS VAULT (8 cards) - The rarest ====================
  {
    cardCode: 'SECRETS_001',
    name: 'The Hidden One',
    description: 'You found a card that shouldn\'t exist. How did you get here?',
    rarity: 'mythic',
    series: 'SECRETS',
    seriesNumber: 1,
    totalInSeries: 8,
    discoveryType: 'secret',
    discoveryTrigger: { easter_egg: 'impossible_path' },
    discoveryHint: '???',
    powerLevel: 180,
    element: 'dark',
    cardType: 'character',
    maxSupply: 50,
    isActive: true,
  },
  {
    cardCode: 'SECRETS_002',
    name: 'Error 404',
    description: 'Found by visiting a page that doesn\'t exist. Sometimes being lost leads to treasure.',
    rarity: 'legendary',
    series: 'SECRETS',
    seriesNumber: 2,
    totalInSeries: 8,
    discoveryType: 'secret',
    discoveryTrigger: { easter_egg: '404_page' },
    discoveryHint: 'Get lost on purpose.',
    powerLevel: 90,
    element: 'neutral',
    cardType: 'event',
    maxSupply: 500,
    isActive: true,
  },
  {
    cardCode: 'SECRETS_003',
    name: 'Console Commander',
    description: 'Opened the developer console. A true power user.',
    rarity: 'legendary',
    series: 'SECRETS',
    seriesNumber: 3,
    totalInSeries: 8,
    discoveryType: 'secret',
    discoveryTrigger: { easter_egg: 'dev_console' },
    discoveryHint: 'Think like a developer.',
    powerLevel: 95,
    element: 'light',
    cardType: 'artifact',
    maxSupply: 1000,
    isActive: true,
  },
  {
    cardCode: 'SECRETS_004',
    name: 'Honus Wagner\'s Ghost',
    description: 'Searched for "T206 Honus Wagner" exactly. The legend acknowledges you.',
    rarity: 'mythic',
    series: 'SECRETS',
    seriesNumber: 4,
    totalInSeries: 8,
    discoveryType: 'secret',
    discoveryTrigger: { search_query: 'T206 Honus Wagner' },
    discoveryHint: 'Search for the holy grail.',
    powerLevel: 200,
    element: 'earth',
    cardType: 'character',
    maxSupply: 100,
    isActive: true,
  },
  {
    cardCode: 'SECRETS_005',
    name: 'Black Lotus Vision',
    description: 'Searched for "Black Lotus Alpha". The Power Nine acknowledges you.',
    rarity: 'mythic',
    series: 'SECRETS',
    seriesNumber: 5,
    totalInSeries: 8,
    discoveryType: 'secret',
    discoveryTrigger: { search_query: 'Black Lotus Alpha' },
    discoveryHint: 'Seek the most powerful card ever printed.',
    powerLevel: 200,
    element: 'dark',
    cardType: 'artifact',
    maxSupply: 100,
    isActive: true,
  },
  {
    cardCode: 'SECRETS_006',
    name: 'Pikachu\'s Blessing',
    description: 'Searched for "Pikachu Illustrator". The rarest Pokémon card blesses you.',
    rarity: 'mythic',
    series: 'SECRETS',
    seriesNumber: 6,
    totalInSeries: 8,
    discoveryType: 'secret',
    discoveryTrigger: { search_query: 'Pikachu Illustrator' },
    discoveryHint: 'The illustrator\'s gift awaits.',
    powerLevel: 200,
    element: 'light',
    cardType: 'character',
    maxSupply: 100,
    isActive: true,
  },
  {
    cardCode: 'SECRETS_007',
    name: 'Midnight Collector',
    description: 'Clicked on a specific pixel at exactly midnight.',
    rarity: 'mythic',
    series: 'SECRETS',
    seriesNumber: 7,
    totalInSeries: 8,
    discoveryType: 'secret',
    discoveryTrigger: { easter_egg: 'midnight_pixel' },
    discoveryHint: 'When the clock strikes twelve, look closely...',
    powerLevel: 175,
    element: 'dark',
    cardType: 'event',
    maxSupply: 25,
    isActive: true,
  },
  {
    cardCode: 'SECRETS_008',
    name: 'Master of Secrets',
    description: 'Found all Secret Vault cards. You have uncovered every mystery.',
    rarity: 'mythic',
    series: 'SECRETS',
    seriesNumber: 8,
    totalInSeries: 8,
    discoveryType: 'collection',
    discoveryTrigger: { series_complete: 'SECRETS' },
    discoveryHint: 'Collect all other Secret Vault cards.',
    powerLevel: 300,
    element: 'neutral',
    cardType: 'character',
    maxSupply: 10,
    isActive: true,
  },
];

// ============================================================================
// HELPER FUNCTIONS
// ============================================================================

export function getCardsByRarity(rarity: Rarity): typeof DIGITAL_CARDS {
  return DIGITAL_CARDS.filter(card => card.rarity === rarity);
}

export function getCardsBySeries(seriesCode: string): typeof DIGITAL_CARDS {
  return DIGITAL_CARDS.filter(card => card.series === seriesCode);
}

export function getRarityConfig(rarity: Rarity) {
  return RARITY_CONFIG[rarity];
}

export function getSeriesProgress(userCards: string[], seriesCode: string) {
  const seriesCards = getCardsBySeries(seriesCode);
  const ownedInSeries = seriesCards.filter(card => userCards.includes(card.cardCode));
  return {
    owned: ownedInSeries.length,
    total: seriesCards.length,
    percentage: Math.round((ownedInSeries.length / seriesCards.length) * 100),
    isComplete: ownedInSeries.length === seriesCards.length,
  };
}

export function canDiscoverCard(
  card: typeof DIGITAL_CARDS[0],
  userProgress: Record<string, unknown>
): boolean {
  // Logic to check if user meets discovery requirements
  const trigger = card.discoveryTrigger;
  
  switch (card.discoveryType) {
    case 'feature_use':
      if (trigger.feature && trigger.uses) {
        const uses = (userProgress.feature_uses as Record<string, number>)?.[trigger.feature as string] || 0;
        return uses >= (trigger.uses as number);
      }
      break;
    case 'streak':
      if (trigger.daily_streak) {
        return (userProgress.daily_login_streak as number) >= (trigger.daily_streak as number);
      }
      break;
    case 'trivia':
      if (trigger.correct_answers) {
        return (userProgress.trivia_correct as number) >= (trigger.correct_answers as number);
      }
      break;
    case 'collection':
      if (trigger.cards_added) {
        return (userProgress.cards_in_collection as number) >= (trigger.cards_added as number);
      }
      break;
    // Add more discovery type checks...
  }
  
  return false;
}

export default {
  RARITY_CONFIG,
  ELEMENTS,
  DISCOVERY_TYPES,
  CARD_SERIES,
  DIGITAL_CARDS,
  getCardsByRarity,
  getCardsBySeries,
  getRarityConfig,
  getSeriesProgress,
  canDiscoverCard,
};
